name: conda_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - cloudpickle=0.7.0=py_0
  - cycler=0.10.0=py36_0
  - dask-core=1.1.1=py_0
  - imageio=2.4.1=py36_0
  - openssl=1.1.1a=h14c3975_1000
  - pip=19.0.1=py36_0
  - pyyaml=3.13=py36h14c3975_1001
  - setuptools=40.7.3=py36_0
  - tensorboardx=1.6=py_0
  - termcolor=1.1.0=py36_1
  - tqdm=4.31.1=py_0
  - wheel=0.32.3=py36_0
  - yacs=0.1.4=py_0
  - yaml=0.1.7=h14c3975_1001
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - cairo=1.14.12=h8948797_3
  - cffi=1.11.5=py36he75722e_1
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.3.1=cuda9.0_0
  - cupti=9.0.176=0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dbus=1.13.6=h746ee38_0
  - decorator=4.3.2=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.6=py36_0
  - keras-preprocessing=1.0.5=py36_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - markdown=3.0.1=py36_0
  - matplotlib=3.0.2=py36h5429711_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.2=py36_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - pcre=8.42=h439df22_0
  - pillow=5.4.1=py36h34e0f95_0
  - pixman=0.36.0=h7b6447c_0
  - protobuf=3.6.1=py36he6710b0_0
  - pycparser=2.19=py36_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.8=h0371630_0
  - python-dateutil=2.7.5=py36_0
  - pytz=2018.9=py36_0
  - pywavelets=1.0.1=py36hdd07704_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.1=py36he6710b0_0
  - scipy=1.2.0=py36h7c811a0_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.26.0=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he68c306_0
  - tensorflow-base=1.12.0=gpu_py36h8e0ae2d_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h7b6447c_0
  - werkzeug=0.14.1=py36_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.1.0=py3.6_cuda9.0.176_cudnn7.5.1_0
  - torchvision=0.2.1=py_2
  - pip:
    - dask==1.1.1
    - keras==2.2.4
    - opencv-contrib-python==3.4.2.17
    - opencv-python==4.0.0.21
    - pafy==0.5.4
    - torch==1.1.0
    - youtube-dl==2019.2.18

